### ISSUE TITLE
Replace /demo with /core, based on dogfooding database

### ISSUE THREAD

**Issue by cpcallen** [google/CodeCity#364]
* [x] Finish dumper sufficiently: #363.
* [x] Review `/core/` to see if there is anything there worth saving; add anything interesting to the production database.
* [x] Move `/demo/` to `/core/` and commit (#372).
* [x] Make additional fixes to dumper (#375)
* [x] Add core code to restart timers, repopulate `Selector.db.map_`, etc.
   * [x] Restart `$.clock`.
   * [x] Clear `$.db.tempId`?
   * [x] Repopulate `Selector.db.map_`.
* [x] ~~Rename `.listeners_` in existing `.city` files to `.listeners`?~~
* [x] Prod push time:
   * [x] Dump the production database, manually edit and overwrite `/core/` with it.  Commit. (#382)
      * [x] Also save non-core world stuff, but don't commit this.
   * [x] Update `prod` branch with `master` and dumped core.
   * [x] Verify dump restarts locally.
   * [x] Update `google.codecity.world` to latest server & new directory layout
      * [x] `git fetch && git checkout prod && git pull`
   * [x] `scp` the `core/` and `database/` contents to prod.
   * [x] Restart server from `.js` files.
       * [x] Verify nothing is too badly broken.
   * [x] Archive `.city` files.

There will probably be a lather / rinse / repeat after permissions have been implemented.
